@isTest
private class PromotionControllerTest{
	@testSetup
	static void setup(){
        //String countryName = 'Belarus';
		//Promotion__c newPromotion = new Promotion__c(Discount__c = 10, EndDate__c = date.today().addMonths(2), Paym__c = 'Plan 1;Plan 2');
		//insert newPromotion;
		//CountrySetting__c countrySetting = new CountrySetting__c(Name = countryName, CurrencyIsoCode = defaultCurrencyIsoCode, Pricebook__c = pricebook.Id);
		//insert countrySetting;
	}

	@isTest
	static void getPromotionsTest(){
	}
}